timemachine:
  image: cptactionhank/netatalk:latest
  container_name: timemachine
  environment:
    - AVAHI=1
  net: host
  ports:
    - 548:548/tcp
  restart: always
  volumes:
    - /storage/backup/timemachine:/media/timemachine
    - /storage/backup/share:/media/share