timemachine:
  command:
    - /entrypoint.sh
  container_name: timemachine
  environment:
    - AFP_LOGIN=cada
    - AFP_PASSWORD=secret
    - AFP_NAME=TimeMachine
  hostname: timemachine
  image: odarriba/timemachine
  ports:
    - 636:636/tcp
    - 548:548/tcp
  restart: unless-stopped
  volumes:
    - /storage/backup/timemachine:/timemachine
